// Angular/todolist-ang/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  // State
  todos: string[] = [];
  todoText = '';

  // Lifecycle
  ngOnInit() {
    const existingTodos = localStorage.getItem('todos');
    this.todos = JSON.parse(existingTodos as string) || [];
  }

  // Events
  addTodo() {
    this.todos.push(this.todoText);
    localStorage.setItem('todos', JSON.stringify(this.todos));
  }
}

// React/todolist/src/App.js
import { useEffect, useRef, useState } from "react";
import "./App.css";

function App() {
  // State
  const [todos, setTodos] = useState([]);

  // Binding
  const todoText = useRef();

  // Side Effects / Lifecycle
  useEffect(() => {
    const existingTodos = localStorage.getItem("todos");
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);

  // Events
  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    todoText.current.value = "";
    localStorage.setItem("todos", JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos.map((todo) => (
          <li key={todo}>{todo}</li>
        ))}
      </ul>

      <form onSubmit={addTodo}>
        <input
          type="text"
          placeholder="What needs to be done?"
          ref={todoText}
        />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  );
}

// const clearLocalStorage = function (storage) {
//   localStorage.clear(storage);
// };
// clearLocalStorage("todos");

export default App;
